language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
os:
  - linux
  - osx
  - windows
node_js:
  - '10'
  - '11'
  - '12'
  - '8'
  - '6'
script:
  - npm run test:prod && npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
